# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Music Goer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Music Goer
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'
  pod 'Firebase/InAppMessaging'
  pod 'GoogleSignIn'
  pod 'FloatingPanel'
  pod 'MessageKit', '~> 3.3.0'
  pod 'InputBarAccessoryView', '5.1.0'

end